wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = false
idle = true
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
frame = "transparent"
title-hidden = true
tabs = true

[font]
normal = { family = "CodeNewRoman Nerd Font Propo", style = "Thin" }
size = 15.0
